# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

        
  # ---------------------------------------------------------------------
  # linux
  # ---------------------------------------------------------------------

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nim dependencies
        run: |
          wget -qO - https://nim-lang.org/choosenim/init.sh > setup_nim.sh
          sh setup_nim.sh -y
      - name: Build library
        run: PATH=/home/runner/.nimble/bin:$PATH ./build.sh
      - uses: actions/upload-artifact@v2
        with:
         name: nmusd-build-linux-artifacts
         path: |
          ./*.sh
          deps/usd/build/inst/lib/
          ./bin/
          ./data/
        
  min-test-linux:
    needs: build-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: nmusd-build-linux-artifacts
          path: ~/nmusd/
      - name: Run minimum test suite
        run: sudo chmod -R +rwx /home/runner/nmusd && cd /home/runner/nmusd && sudo sh ./run.sh
  
  full-test-linux:
    needs: min-test-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: nmusd-build-linux-artifacts
          path: ~/nmusd/
      - name: Run minimum test suite
        run: sudo chmod -R +rwx /home/runner/nmusd && cd /home/runner/nmusd && sudo sh ./run.sh
        
  min-bench-linux:
    needs: build-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: nmusd-build-linux-artifacts
          path: ~/nmusd/
      - name: Run minimum test suite
        run: sudo chmod -R +rwx /home/runner/nmusd && cd /home/runner/nmusd && sudo sh ./run.sh
        
  full-bench-linux:
    needs: min-bench-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: nmusd-build-linux
          path: ~/nmusd/
      - name: Run minimum test suite
        run: sudo chmod -R +rwx /home/runner/nmusd && cd /home/runner/nmusd && sudo sh ./run.sh
        
  fuzz-linux:
    needs: [full-bench-linux, full-test-linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: nmusd-build-linux
          path: ~/nmusd/
      - name: Run minimum test suite
        run: echo "Hello, placeholder"
        
        
  # ---------------------------------------------------------------------
  # macos
  # ---------------------------------------------------------------------

  build-macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Install nim dependencies
        run: |
          wget -qO - https://nim-lang.org/choosenim/init.sh > setup_nim.sh
          sh setup_nim.sh -y
      - name: Build library
        run: PATH=/home/runner/.nimble/bin:$PATH ./build.sh
      - uses: actions/upload-artifact@v2
        with:
         name: nmusd-build-macos-artifacts
         path: |
          ./*.sh
          deps/usd/build/inst/lib/
          ./bin/
          ./data/
  
  min-test-macos:
    needs: build-macos
    runs-on: macos-11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: nmusd-build-macos-artifacts
          path: ~/nmusd/
      - name: Run minimum test suite
        run: echo "Placeholder"
        
  
  full-test-macos:
    needs: min-test-macos
    runs-on: macos-11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: nmusd-build-macos-artifacts
          path: ~/nmusd/
      - name: Run minimum test suite
        run: echo "Placeholder"
     
  min-bench-macos:
    needs: build-macos
    runs-on: macos-11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: nmusd-build-macos-artifacts
          path: ~/nmusd/
      - name: Run minimum test suite
        run: echo "Placeholder"
  
  full-bench-macos:
    needs: min-bench-macos
    runs-on: macos-11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: nmusd-build-macos-artifacts
          path: ~/nmusd/
      - name: Run minimum test suite
        run: echo "Placeholder"
        
  fuzz-macos:
    needs: [full-bench-macos, full-test-macos]
    runs-on: macos-11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: nmusd-build-linux
          path: ~/nmusd/
      - name: Run minimum test suite
        run: echo "Hello, placeholder"
  
  # ---------------------------------------------------------------------
  # macos
  # ---------------------------------------------------------------------
          
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: docker build -t nmusd_env .
      - name: Tar container
        run: docker save nmusd_env > nmusd_env.tar
      - uses: actions/upload-artifact@v2
        with:
         name: nmusd-build-docker-artifacts
         path: nmusd_env_tar

  min-test-docker:
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: nmusd-build-macos-artifacts
          path: ~/nmusd/
      - name: Run minimum test suite
        run: echo "Placeholder"

  full-test-docker:
    needs: min-test-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: nmusd-build-macos-artifacts
          path: ~/nmusd/
      - name: Run minimum test suite
        run: echo "Placeholder"
        
  min-bench-docker:
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: nmusd-build-macos-artifacts
          path: ~/nmusd/
      - name: Run minimum test suite
        run: echo "Placeholder"

  full-bench-docker:
    needs: min-bench-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: nmusd-build-macos-artifacts
          path: ~/nmusd/
      - name: Run minimum test suite
        run: echo "Placeholder"

  fuzz-docker:
    needs: [full-bench-docker, full-test-docker]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: nmusd-build-linux
          path: ~/nmusd/
      - name: Run minimum test suite
        run: echo "Hello, placeholder"
  

  # ---------------------------------------------------------------------
  # universal
  # ---------------------------------------------------------------------
          
  nimble-publish:
    runs-on: ubuntu-latest
    needs: [fuzz-linux, fuzz-macos, full-test-docker]
    steps:
      - uses: actions/checkout@v2
      - name: Assemble nimble package
        run: echo "Placeholder"
